# 项目相关配置
project:
  # 名称
  name: getoffer
  # 版本
  version: 1.0
  # 版权年份
  copyrightYear: 2019
  #swagger 文档配置
  swagger:
    title: GetOffer微信小程序个人中心接口
    description: 开发人员太懒，没有写描述
    contactName: Fengyu
    contactEmail: 475788922@qq.com
    contactUrl: https://getoffer.xiliangmen.com/doc.html
    version: 1.0
  wx:
    applet:
      configs:
        appid: 123
        secret: 456
    pay:
      appId: 123
      mchId: 123
      mchKey: 123
      keyPath: 123


mybatis-plus:
  # 搜索指定包别名
  typeAliasesPackage: com.belong
  # 配置mapper的扫描，找到所有的mapper.xml映射文件
  mapperLocations: classpath*:mapper/**/*Mapper.xml
  global-config:
    #刷新mapper 调试神器
    db-config:
      id-type: UUID
      field-strategy: not_empty
      #驼峰下划线转换
      column-underline: true
      #逻辑删除配置
      logic-delete-value: 0
      logic-not-delete-value: 1
      db-type: mysql
    refresh: true
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    #    日志打印
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl



#lcn配置
tx-lcn:
  client:
    manager-address: 127.0.0.1:8070
  springcloud:
    loadbalance:
#      为保证性能开启TX-LCN重写的负载策略
      enabled: true

security:
  jwt:
    secret: k09BQnaF
    expiration: 604800 #7Days